"""
Cable and Cable Type models for Phase 2 Cable Generation.

This module defines the database models for:
- Cable: Individual cable instances connecting assets
- CableType: Cable catalog with manufacturer specifications
- CableSizingRule: Electrical code rules for cable sizing
"""

import uuid
from datetime import datetime

from sqlalchemy import JSON, TIMESTAMP, Boolean, Column, Float, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.core.database import Base


class Cable(Base):
    """
    Represents a physical cable connecting two assets.

    Cables are generated by rules (CREATE_CABLE action) or created manually.
    Includes electrical sizing calculations and compliance tracking.
    """

    __tablename__ = "cables"

    # Primary Key
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id = Column(String, ForeignKey("projects.id"), nullable=False, index=True)

    # Cable Identification
    tag = Column(String(50), nullable=False, index=True)  # e.g., "310-PP-001-PWR"
    cable_type = Column(String(50), index=True)  # "POWER", "SIGNAL", "FIBER", "CONTROL"
    description = Column(Text)

    # Connections
    from_asset_id = Column(String, ForeignKey("assets.id"), index=True)
    from_terminal = Column(String(50))  # Terminal designation on source asset
    to_asset_id = Column(String, ForeignKey("assets.id"), index=True)
    to_terminal = Column(String(50))  # Terminal designation on destination asset

    # Cable Specifications
    conductor_size = Column(String(20))  # "3x10 AWG", "4x2.5mm²"
    construction = Column(String(100))  # "3C+1G", "2x2x0.75mm² Shielded"
    conductor_material = Column(String(20), default="Copper")  # "Copper", "Aluminum"
    insulation_type = Column(String(50))  # "XLPE", "PVC", "EPR"
    armor_type = Column(String(50))  # "SWA", "Braided", "None"
    sheath_material = Column(String(50))  # "PVC", "LSZH"

    # Cable Route
    length_meters = Column(Float)
    route_description = Column(Text)
    installation_method = Column(String(50))  # "Tray", "Conduit", "Direct Burial", "Overhead"
    conduit_size = Column(String(20))  # "2 inch", "50mm"

    # Electrical Properties (calculated)
    voltage_rating = Column(String(20))  # "600V", "1000V"
    current_rating_amps = Column(Float)
    voltage_drop_volts = Column(Float)
    voltage_drop_percent = Column(Float)
    power_loss_watts = Column(Float)

    # Standards & Compliance
    code_standard = Column(String(50))  # "CEC-2021", "NEC-2023", "IEC-60364"
    temperature_rating = Column(String(20))  # "75°C", "90°C"
    flame_rating = Column(String(50))  # "LSZH", "Flame Retardant"

    # Cable Catalog Reference (optional)
    cable_type_id = Column(UUID(as_uuid=True), ForeignKey("cable_types.id"))
    manufacturer = Column(String(100))
    part_number = Column(String(100))

    # Additional Properties (JSON for flexibility)
    properties = Column(JSON, default={})

    # Rule Tracking
    created_by_rule_id = Column(String, ForeignKey("rule_definitions.id"))

    # Status
    is_active = Column(Boolean, default=True)
    status = Column(String(20), default="PROPOSED")  # "PROPOSED", "APPROVED", "INSTALLED"

    # Metadata
    created_at = Column(TIMESTAMP, default=datetime.utcnow)
    updated_at = Column(TIMESTAMP, default=datetime.utcnow, onupdate=datetime.utcnow)
    created_by = Column(String(100))
    notes = Column(Text)

    # Relationships
    from_asset = relationship("Asset", foreign_keys=[from_asset_id], backref="cables_from")
    to_asset = relationship("Asset", foreign_keys=[to_asset_id], backref="cables_to")
    created_by_rule = relationship("RuleDefinition", backref="cables_created")
    cable_catalog = relationship("CableType", backref="cable_instances")

    def __repr__(self):
        return f"<Cable {self.tag} ({self.cable_type})>"


class CableType(Base):
    """
    Cable catalog with manufacturer specifications.

    Used for selecting appropriate cables from vendor catalogs
    and standardizing cable specifications across projects.
    """

    __tablename__ = "cable_types"

    # Primary Key
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Type Identification
    manufacturer = Column(String(100), index=True)  # "Prysmian", "Nexans", "Lapp", "Southwire"
    part_number = Column(String(100), index=True)
    description = Column(Text)
    cable_family = Column(String(100))  # "NYY", "THHN", "VFD Cable"

    # Specifications
    cable_type = Column(String(50), index=True)  # "POWER", "SIGNAL", "CONTROL"
    conductor_material = Column(String(20), default="Copper")
    conductor_size = Column(String(20))  # "10 AWG", "2.5mm²"
    number_of_conductors = Column(Integer)
    construction = Column(String(100))  # "Stranded", "Solid"
    insulation_type = Column(String(50))
    armor_type = Column(String(50))
    sheath_material = Column(String(50))

    # Electrical Ratings
    voltage_rating = Column(String(20))
    current_rating_amps = Column(Float)
    temperature_rating = Column(String(20))

    # Standards Compliance
    standards = Column(JSON, default=[])  # ["UL 44", "IEC 60502", "CSA C22.2 No. 75"]

    # Physical Properties
    outer_diameter_mm = Column(Float)
    weight_kg_per_m = Column(Float)
    min_bend_radius_mm = Column(Float)

    # Environmental
    temp_range_celsius = Column(String(50))  # "-40 to 90°C"
    flame_rating = Column(String(50))
    outdoor_rated = Column(Boolean, default=False)
    sunlight_resistant = Column(Boolean, default=False)
    oil_resistant = Column(Boolean, default=False)

    # Pricing (optional)
    unit_price_per_m = Column(Float)
    currency = Column(String(10), default="USD")
    lead_time_days = Column(Integer)

    # Additional Properties
    properties = Column(JSON, default={})

    # Metadata
    created_at = Column(TIMESTAMP, default=datetime.utcnow)
    updated_at = Column(TIMESTAMP, default=datetime.utcnow, onupdate=datetime.utcnow)
    is_active = Column(Boolean, default=True)

    def __repr__(self):
        return f"<CableType {self.manufacturer} {self.part_number}>"


class CableSizingRule(Base):
    """
    Electrical code rules for cable sizing calculations.

    Stores ampacity tables, derating factors, and voltage drop
    requirements from CEC, NEC, IEC standards.
    """

    __tablename__ = "cable_sizing_rules"

    # Primary Key
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Rule Definition
    code_standard = Column(
        String(50), nullable=False, index=True
    )  # "CEC-2021", "NEC-2023", "IEC-60364"
    voltage_level = Column(String(20), index=True)  # "600V", "480V", "400V", "1000V"
    application = Column(String(50), index=True)  # "Motor - Continuous", "Heater", "Lighting"

    # Conductor Specifications
    conductor_size = Column(String(20), nullable=False)  # "10 AWG", "2.5mm²"
    conductor_material = Column(String(20), default="Copper")
    insulation_type = Column(String(50))  # "RW90 XLPE", "THHN", "PVC"
    temperature_rating = Column(String(20))  # "75°C", "90°C"

    # Ampacity
    ampacity_amps = Column(Float, nullable=False)  # Base ampacity at reference conditions

    # Derating Factors
    derating_factors = Column(JSON, default={})  # {
    #   "temperature": {"30C": 1.0, "40C": 0.91},
    #   "grouping": {"1-3": 1.0, "4-6": 0.8},
    #   "conduit_fill": {"40%": 1.0, "60%": 0.8}
    # }

    # Voltage Drop
    max_voltage_drop_percent = Column(Float)  # Maximum allowed voltage drop (e.g., 3%)
    resistance_ohm_per_km = Column(Float)  # Conductor resistance
    reactance_ohm_per_km = Column(Float)  # Conductor reactance (for AC calculations)

    # Reference
    code_reference = Column(String(200))  # "CEC Table 2, Rule 8-104"
    table_number = Column(String(50))  # "Table 2", "Table 310.16"
    notes = Column(Text)

    # Additional Properties
    properties = Column(JSON, default={})

    # Metadata
    created_at = Column(TIMESTAMP, default=datetime.utcnow)
    is_active = Column(Boolean, default=True)

    def __repr__(self):
        return (
            f"<CableSizingRule {self.code_standard} {self.conductor_size} @ {self.ampacity_amps}A>"
        )
