"""drop_metamodel_edge_fks

Revision ID: 01b0b839868f
Revises: 17c450ee558b
Create Date: 2025-11-22 23:56:50.886103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b0b839868f'
down_revision: Union[str, None] = '17c450ee558b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('metamodel_edges_source_node_id_fkey', 'metamodel_edges', type_='foreignkey')
    op.drop_constraint('metamodel_edges_target_node_id_fkey', 'metamodel_edges', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('metamodel_edges_target_node_id_fkey', 'metamodel_edges', 'metamodel_nodes', ['target_node_id'], ['id'])
    op.create_foreign_key('metamodel_edges_source_node_id_fkey', 'metamodel_edges', 'metamodel_nodes', ['source_node_id'], ['id'])
    # ### end Alembic commands ###
