"""Add ingestion models and asset confidence

Revision ID: 6f5972dbcbb6
Revises: a678a9de6eb4
Create Date: 2025-11-21 22:14:31.260304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f5972dbcbb6'
down_revision: Union[str, None] = 'a678a9de6eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('ingest_status', sa.Enum('PENDING', 'STAGED', 'MAPPED', 'IMPORTED', 'ERROR', name='ingeststatus'), nullable=True),
    sa.Column('detected_type', sa.Enum('BBA_INSTRUMENT_LIST', 'CABLE_SCHEDULE', 'GENERIC_LIST', 'UNKNOWN', name='detectedtype'), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('staged_rows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('data_source_id', sa.String(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('import_status', sa.Enum('PENDING', 'SKIPPED', 'IMPORTED', 'ERROR', name='importstatus'), nullable=True),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('assets', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('data_source_id', sa.String(), nullable=True))
    op.add_column('metamodel_nodes', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('metamodel_nodes', sa.Column('data_source_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metamodel_nodes', 'data_source_id')
    op.drop_column('metamodel_nodes', 'confidence_score')
    op.drop_column('assets', 'data_source_id')
    op.drop_column('assets', 'confidence_score')
    op.drop_table('staged_rows')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
