"""add_rule_validation_and_asset_data_statuses

Revision ID: 72e11ad0ddbd
Revises: a1b2c3d4e5f6
Create Date: 2025-11-21 21:48:26.191612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e11ad0ddbd'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create Enums manually
    op.execute("CREATE TYPE assetdatastatus AS ENUM ('FRESH_IMPORT', 'IN_REVIEW', 'VALIDATED', 'ERROR')")
    op.execute("CREATE TYPE rulevalidationstatus AS ENUM ('DRAFT', 'DEV_VALIDATED', 'PROD_READY', 'DEPRECATED')")

    op.add_column('metamodel_nodes', sa.Column('data_status', sa.Enum('FRESH_IMPORT', 'IN_REVIEW', 'VALIDATED', 'ERROR', name='assetdatastatus'), nullable=True))
    op.create_index(op.f('ix_metamodel_nodes_data_status'), 'metamodel_nodes', ['data_status'], unique=False)
    op.add_column('rule_definitions', sa.Column('validation_status', sa.Enum('DRAFT', 'DEV_VALIDATED', 'PROD_READY', 'DEPRECATED', name='rulevalidationstatus'), nullable=True))
    op.alter_column('rule_definitions', 'is_enforced',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index(op.f('ix_rule_definitions_validation_status'), 'rule_definitions', ['validation_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rule_definitions_validation_status'), table_name='rule_definitions')
    op.alter_column('rule_definitions', 'is_enforced',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('rule_definitions', 'validation_status')
    op.drop_index(op.f('ix_metamodel_nodes_data_status'), table_name='metamodel_nodes')
    op.drop_column('metamodel_nodes', 'data_status')
    
    # Drop Enums manually
    op.execute("DROP TYPE rulevalidationstatus")
    op.execute("DROP TYPE assetdatastatus")
    # ### end Alembic commands ###
