"""Add cable tables final fix

Revision ID: d21466a69190
Revises: 6faa9ed84b81
Create Date: 2025-11-22 14:22:23.314832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21466a69190'
down_revision: Union[str, None] = '6faa9ed84b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cable_sizing_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_standard', sa.String(length=50), nullable=False),
    sa.Column('voltage_level', sa.String(length=20), nullable=True),
    sa.Column('application', sa.String(length=50), nullable=True),
    sa.Column('conductor_size', sa.String(length=20), nullable=False),
    sa.Column('conductor_material', sa.String(length=20), nullable=True),
    sa.Column('insulation_type', sa.String(length=50), nullable=True),
    sa.Column('temperature_rating', sa.String(length=20), nullable=True),
    sa.Column('ampacity_amps', sa.Float(), nullable=False),
    sa.Column('derating_factors', sa.JSON(), nullable=True),
    sa.Column('max_voltage_drop_percent', sa.Float(), nullable=True),
    sa.Column('resistance_ohm_per_km', sa.Float(), nullable=True),
    sa.Column('reactance_ohm_per_km', sa.Float(), nullable=True),
    sa.Column('code_reference', sa.String(length=200), nullable=True),
    sa.Column('table_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cable_sizing_rules_application'), 'cable_sizing_rules', ['application'], unique=False)
    op.create_index(op.f('ix_cable_sizing_rules_code_standard'), 'cable_sizing_rules', ['code_standard'], unique=False)
    op.create_index(op.f('ix_cable_sizing_rules_voltage_level'), 'cable_sizing_rules', ['voltage_level'], unique=False)
    op.create_table('cable_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('part_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cable_family', sa.String(length=100), nullable=True),
    sa.Column('cable_type', sa.String(length=50), nullable=True),
    sa.Column('conductor_material', sa.String(length=20), nullable=True),
    sa.Column('conductor_size', sa.String(length=20), nullable=True),
    sa.Column('number_of_conductors', sa.Integer(), nullable=True),
    sa.Column('construction', sa.String(length=100), nullable=True),
    sa.Column('insulation_type', sa.String(length=50), nullable=True),
    sa.Column('armor_type', sa.String(length=50), nullable=True),
    sa.Column('sheath_material', sa.String(length=50), nullable=True),
    sa.Column('voltage_rating', sa.String(length=20), nullable=True),
    sa.Column('current_rating_amps', sa.Float(), nullable=True),
    sa.Column('temperature_rating', sa.String(length=20), nullable=True),
    sa.Column('standards', sa.JSON(), nullable=True),
    sa.Column('outer_diameter_mm', sa.Float(), nullable=True),
    sa.Column('weight_kg_per_m', sa.Float(), nullable=True),
    sa.Column('min_bend_radius_mm', sa.Float(), nullable=True),
    sa.Column('temp_range_celsius', sa.String(length=50), nullable=True),
    sa.Column('flame_rating', sa.String(length=50), nullable=True),
    sa.Column('outdoor_rated', sa.Boolean(), nullable=True),
    sa.Column('sunlight_resistant', sa.Boolean(), nullable=True),
    sa.Column('oil_resistant', sa.Boolean(), nullable=True),
    sa.Column('unit_price_per_m', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cable_types_cable_type'), 'cable_types', ['cable_type'], unique=False)
    op.create_index(op.f('ix_cable_types_manufacturer'), 'cable_types', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_cable_types_part_number'), 'cable_types', ['part_number'], unique=False)
    op.create_table('cables',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('cable_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('from_asset_id', sa.String(), nullable=True),
    sa.Column('from_terminal', sa.String(length=50), nullable=True),
    sa.Column('to_asset_id', sa.String(), nullable=True),
    sa.Column('to_terminal', sa.String(length=50), nullable=True),
    sa.Column('conductor_size', sa.String(length=20), nullable=True),
    sa.Column('construction', sa.String(length=100), nullable=True),
    sa.Column('conductor_material', sa.String(length=20), nullable=True),
    sa.Column('insulation_type', sa.String(length=50), nullable=True),
    sa.Column('armor_type', sa.String(length=50), nullable=True),
    sa.Column('sheath_material', sa.String(length=50), nullable=True),
    sa.Column('length_meters', sa.Float(), nullable=True),
    sa.Column('route_description', sa.Text(), nullable=True),
    sa.Column('installation_method', sa.String(length=50), nullable=True),
    sa.Column('conduit_size', sa.String(length=20), nullable=True),
    sa.Column('voltage_rating', sa.String(length=20), nullable=True),
    sa.Column('current_rating_amps', sa.Float(), nullable=True),
    sa.Column('voltage_drop_volts', sa.Float(), nullable=True),
    sa.Column('voltage_drop_percent', sa.Float(), nullable=True),
    sa.Column('power_loss_watts', sa.Float(), nullable=True),
    sa.Column('code_standard', sa.String(length=50), nullable=True),
    sa.Column('temperature_rating', sa.String(length=20), nullable=True),
    sa.Column('flame_rating', sa.String(length=50), nullable=True),
    sa.Column('cable_type_id', sa.UUID(), nullable=True),
    sa.Column('manufacturer', sa.String(length=100), nullable=True),
    sa.Column('part_number', sa.String(length=100), nullable=True),
    sa.Column('properties', sa.JSON(), nullable=True),
    sa.Column('created_by_rule_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cable_type_id'], ['cable_types.id'], ),
    sa.ForeignKeyConstraint(['created_by_rule_id'], ['rule_definitions.id'], ),
    sa.ForeignKeyConstraint(['from_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['to_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cables_cable_type'), 'cables', ['cable_type'], unique=False)
    op.create_index(op.f('ix_cables_from_asset_id'), 'cables', ['from_asset_id'], unique=False)
    op.create_index(op.f('ix_cables_project_id'), 'cables', ['project_id'], unique=False)
    op.create_index(op.f('ix_cables_tag'), 'cables', ['tag'], unique=False)
    op.create_index(op.f('ix_cables_to_asset_id'), 'cables', ['to_asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cables_to_asset_id'), table_name='cables')
    op.drop_index(op.f('ix_cables_tag'), table_name='cables')
    op.drop_index(op.f('ix_cables_project_id'), table_name='cables')
    op.drop_index(op.f('ix_cables_from_asset_id'), table_name='cables')
    op.drop_index(op.f('ix_cables_cable_type'), table_name='cables')
    op.drop_table('cables')
    op.drop_index(op.f('ix_cable_types_part_number'), table_name='cable_types')
    op.drop_index(op.f('ix_cable_types_manufacturer'), table_name='cable_types')
    op.drop_index(op.f('ix_cable_types_cable_type'), table_name='cable_types')
    op.drop_table('cable_types')
    op.drop_index(op.f('ix_cable_sizing_rules_voltage_level'), table_name='cable_sizing_rules')
    op.drop_index(op.f('ix_cable_sizing_rules_code_standard'), table_name='cable_sizing_rules')
    op.drop_index(op.f('ix_cable_sizing_rules_application'), table_name='cable_sizing_rules')
    op.drop_table('cable_sizing_rules')
    # ### end Alembic commands ###
