"""Add action_logs table

Revision ID: d2b09ee54e28
Revises: e52556cb3b94
Create Date: 2025-11-20 22:29:01.857191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2b09ee54e28'
down_revision: Union[str, None] = 'e52556cb3b94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.Enum('RULE_EXECUTION', 'CREATE', 'UPDATE', 'LINK', 'ERROR', name='actiontype'), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('discipline', sa.Enum('PROCESS', 'ELECTRICAL', 'AUTOMATION', 'PROCUREMENT', 'MECHANICAL', 'PROJECT', name='disciplinetype'), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'ROLLED_BACK', 'FAILED', name='actionstatus'), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['action_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action_logs')
    op.execute('DROP TYPE actiontype')
    op.execute('DROP TYPE actionstatus')
    # Note: disciplinetype is shared with metamodel, so we don't drop it
    # ### end Alembic commands ###
