"""add_package_type_and_metadata_fields

Revision ID: e6461479a363
Revises: 4f51457cb3c5
Create Date: 2025-11-29 01:42:41.782924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6461479a363'
down_revision: Union[str, None] = '4f51457cb3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('action_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_asset_changes_asset', 'asset_changes', ['asset_id'], unique=False)
    op.create_index('ix_asset_changes_event', 'asset_changes', ['event_id'], unique=False)
    op.create_index('ix_asset_versions_batch', 'asset_versions', ['batch_id'], unique=False)
    op.drop_index(op.f('ix_assets_project_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_type_project'), table_name='assets')
    op.create_index('ix_asset_project_id', 'assets', ['project_id'], unique=False)
    op.create_index('ix_asset_type_project', 'assets', ['type', 'project_id'], unique=False)
    op.add_column('audit_logs', sa.Column('target_type', sa.String(), nullable=False))
    op.add_column('audit_logs', sa.Column('target_id', sa.String(), nullable=False))
    op.add_column('audit_logs', sa.Column('details', sa.JSON(), nullable=True))
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('audit_logs_project_id_fkey'), 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'project_id')
    op.drop_column('audit_logs', 'entity_type')
    op.drop_column('audit_logs', 'entity_id')
    op.drop_column('audit_logs', 'changes')
    op.alter_column('batch_operations', 'is_rolled_back',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_index('ix_batch_operations_project_started', 'batch_operations', ['project_id', 'started_at'], unique=False)
    op.add_column('cable_sizing_rules', sa.Column('application', sa.String(length=50), nullable=True))
    op.add_column('cable_sizing_rules', sa.Column('conductor_material', sa.String(length=20), nullable=True))
    op.add_column('cable_sizing_rules', sa.Column('insulation_type', sa.String(length=50), nullable=True))
    op.add_column('cable_sizing_rules', sa.Column('temperature_rating', sa.String(length=20), nullable=True))
    op.add_column('cable_sizing_rules', sa.Column('max_voltage_drop_percent', sa.Float(), nullable=True))
    op.add_column('cable_sizing_rules', sa.Column('reactance_ohm_per_km', sa.Float(), nullable=True))
    op.add_column('cable_sizing_rules', sa.Column('code_reference', sa.String(length=200), nullable=True))
    op.add_column('cable_sizing_rules', sa.Column('table_number', sa.String(length=50), nullable=True))
    op.add_column('cable_sizing_rules', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('cable_sizing_rules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_cable_sizing_rules_application'), 'cable_sizing_rules', ['application'], unique=False)
    op.create_index(op.f('ix_cable_sizing_rules_voltage_level'), 'cable_sizing_rules', ['voltage_level'], unique=False)
    op.add_column('cable_types', sa.Column('construction', sa.String(length=100), nullable=True))
    op.add_column('cable_types', sa.Column('armor_type', sa.String(length=50), nullable=True))
    op.add_column('cable_types', sa.Column('sheath_material', sa.String(length=50), nullable=True))
    op.add_column('cable_types', sa.Column('temperature_rating', sa.String(length=20), nullable=True))
    op.add_column('cable_types', sa.Column('standards', sa.JSON(), nullable=True))
    op.add_column('cable_types', sa.Column('outer_diameter_mm', sa.Float(), nullable=True))
    op.add_column('cable_types', sa.Column('weight_kg_per_m', sa.Float(), nullable=True))
    op.add_column('cable_types', sa.Column('min_bend_radius_mm', sa.Float(), nullable=True))
    op.add_column('cable_types', sa.Column('temp_range_celsius', sa.String(length=50), nullable=True))
    op.add_column('cable_types', sa.Column('flame_rating', sa.String(length=50), nullable=True))
    op.add_column('cable_types', sa.Column('outdoor_rated', sa.Boolean(), nullable=True))
    op.add_column('cable_types', sa.Column('sunlight_resistant', sa.Boolean(), nullable=True))
    op.add_column('cable_types', sa.Column('oil_resistant', sa.Boolean(), nullable=True))
    op.add_column('cable_types', sa.Column('unit_price_per_m', sa.Float(), nullable=True))
    op.add_column('cable_types', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('cable_types', sa.Column('lead_time_days', sa.Integer(), nullable=True))
    op.add_column('cable_types', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.alter_column('cable_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_cable_types_part_number'), 'cable_types', ['part_number'], unique=False)
    op.add_column('cables', sa.Column('from_terminal', sa.String(length=50), nullable=True))
    op.add_column('cables', sa.Column('to_terminal', sa.String(length=50), nullable=True))
    op.add_column('cables', sa.Column('construction', sa.String(length=100), nullable=True))
    op.add_column('cables', sa.Column('conductor_material', sa.String(length=20), nullable=True))
    op.add_column('cables', sa.Column('insulation_type', sa.String(length=50), nullable=True))
    op.add_column('cables', sa.Column('armor_type', sa.String(length=50), nullable=True))
    op.add_column('cables', sa.Column('sheath_material', sa.String(length=50), nullable=True))
    op.add_column('cables', sa.Column('route_description', sa.Text(), nullable=True))
    op.add_column('cables', sa.Column('installation_method', sa.String(length=50), nullable=True))
    op.add_column('cables', sa.Column('conduit_size', sa.String(length=20), nullable=True))
    op.add_column('cables', sa.Column('voltage_rating', sa.String(length=20), nullable=True))
    op.add_column('cables', sa.Column('current_rating_amps', sa.Float(), nullable=True))
    op.add_column('cables', sa.Column('power_loss_watts', sa.Float(), nullable=True))
    op.add_column('cables', sa.Column('temperature_rating', sa.String(length=20), nullable=True))
    op.add_column('cables', sa.Column('flame_rating', sa.String(length=50), nullable=True))
    op.add_column('cables', sa.Column('manufacturer', sa.String(length=100), nullable=True))
    op.add_column('cables', sa.Column('part_number', sa.String(length=100), nullable=True))
    op.add_column('cables', sa.Column('created_by', sa.String(length=100), nullable=True))
    op.add_column('cables', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('cables', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cables', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_cables_from_asset_id'), 'cables', ['from_asset_id'], unique=False)
    op.create_index(op.f('ix_cables_to_asset_id'), 'cables', ['to_asset_id'], unique=False)
    op.drop_index(op.f('ix_connections_project_id'), table_name='connections')
    op.create_index('ix_connection_project_id', 'connections', ['project_id'], unique=False)
    op.add_column('data_sources', sa.Column('file_hash', sa.String(), nullable=True))
    op.add_column('data_sources', sa.Column('ingest_status', sa.Enum('PENDING', 'STAGED', 'MAPPED', 'IMPORTED', 'ERROR', name='ingeststatus'), nullable=True))
    op.add_column('data_sources', sa.Column('detected_type', sa.Enum('BBA_INSTRUMENT_LIST', 'CABLE_SCHEDULE', 'GENERIC_LIST', 'UNKNOWN', name='detectedtype'), nullable=True))
    op.add_column('data_sources', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('data_sources', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('data_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_data_sources_project_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_status'), table_name='data_sources')
    op.drop_constraint(op.f('data_sources_project_id_fkey'), 'data_sources', type_='foreignkey')
    op.drop_constraint(op.f('data_sources_uploaded_by_fkey'), 'data_sources', type_='foreignkey')
    op.drop_column('data_sources', 'file_type')
    op.drop_column('data_sources', 'uploaded_by')
    op.drop_column('data_sources', 'error_message')
    op.drop_column('data_sources', 'status')
    op.drop_column('data_sources', 'completed_at')
    op.drop_column('data_sources', 'stats')
    op.drop_column('data_sources', 'column_mapping')
    op.drop_column('data_sources', 'file_size')
    op.drop_column('data_sources', 'column_count')
    op.drop_column('data_sources', 'headers')
    op.drop_column('data_sources', 'row_count')
    op.drop_index(op.f('ix_lbs_nodes_project_id'), table_name='lbs_nodes')
    op.create_index('ix_lbs_project_id', 'lbs_nodes', ['project_id'], unique=False)
    op.alter_column('metamodel_edges', 'discipline',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PROCESS', 'ELECTRICAL', 'AUTOMATION', 'MECHANICAL', 'PROJECT', 'PROCUREMENT', 'GENERAL', name='disciplinetype'),
               existing_nullable=True,
               postgresql_using='discipline::disciplinetype')
    op.drop_index(op.f('ix_metamodel_edges_relation'), table_name='metamodel_edges')
    op.drop_index(op.f('ix_metamodel_edges_source'), table_name='metamodel_edges')
    op.drop_index(op.f('ix_metamodel_edges_target'), table_name='metamodel_edges')
    op.create_unique_constraint('uix_metamodel_edge', 'metamodel_edges', ['source_node_id', 'target_node_id', 'relation_type'])
    op.add_column('metamodel_nodes', sa.Column('description', sa.String(), nullable=True))
    op.add_column('metamodel_nodes', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('metamodel_nodes', sa.Column('data_source_id', sa.String(), nullable=True))
    op.alter_column('metamodel_nodes', 'semantic_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('CONTAINER', 'ASSET', 'LINK', name='semantictype'),
               existing_nullable=True,
               postgresql_using='semantic_type::semantictype')
    op.drop_index(op.f('ix_metamodel_nodes_discipline'), table_name='metamodel_nodes')
    op.drop_index(op.f('ix_metamodel_nodes_project_id'), table_name='metamodel_nodes')
    op.drop_index(op.f('ix_metamodel_nodes_type'), table_name='metamodel_nodes')
    op.drop_constraint(op.f('metamodel_nodes_project_id_fkey'), 'metamodel_nodes', type_='foreignkey')
    op.add_column('packages', sa.Column('package_type', sa.String(), nullable=True))
    op.add_column('packages', sa.Column('metadata', sa.JSON(), nullable=True))
    op.alter_column('packages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('packages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_property_changes_version', 'property_changes', ['version_id'], unique=False)
    op.alter_column('rule_definitions', 'is_enforced',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('rule_definitions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('rule_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rule_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rule_definitions', 'version',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('rule_definitions', 'execution_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('rule_definitions', 'last_executed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('rule_definitions', 'success_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('rule_definitions', 'failure_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('rule_executions', 'condition_matched',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('rule_executions', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.add_column('staged_rows', sa.Column('row_index', sa.Integer(), nullable=False))
    op.add_column('staged_rows', sa.Column('import_status', sa.Enum('PENDING', 'SKIPPED', 'IMPORTED', 'ERROR', name='importstatus'), nullable=True))
    op.add_column('staged_rows', sa.Column('asset_id', sa.String(), nullable=True))
    op.add_column('staged_rows', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('staged_rows', 'raw_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_staged_rows_data_source_id'), table_name='staged_rows')
    op.drop_index(op.f('ix_staged_rows_status'), table_name='staged_rows')
    op.drop_constraint(op.f('staged_rows_created_asset_id_fkey'), 'staged_rows', type_='foreignkey')
    op.drop_column('staged_rows', 'validation_errors')
    op.drop_column('staged_rows', 'status')
    op.drop_column('staged_rows', 'mapped_data')
    op.drop_column('staged_rows', 'row_number')
    op.drop_column('staged_rows', 'detected_type')
    op.drop_column('staged_rows', 'created_asset_id')
    op.create_index('ix_workflow_events_breakdown', 'workflow_events', ['fbs_code', 'lbs_code', 'discipline'], unique=False)
    op.create_index('ix_workflow_events_correlation', 'workflow_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_workflow_events_discipline'), 'workflow_events', ['discipline'], unique=False)
    op.create_index(op.f('ix_workflow_events_entity_id'), 'workflow_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_workflow_events_entity_type'), 'workflow_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_workflow_events_fbs_code'), 'workflow_events', ['fbs_code'], unique=False)
    op.create_index(op.f('ix_workflow_events_lbs_code'), 'workflow_events', ['lbs_code'], unique=False)
    op.create_index(op.f('ix_workflow_events_package_code'), 'workflow_events', ['package_code'], unique=False)
    op.create_index('ix_workflow_events_session', 'workflow_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_workflow_events_session_id'), 'workflow_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_events_session_id'), table_name='workflow_events')
    op.drop_index('ix_workflow_events_session', table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_package_code'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_lbs_code'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_fbs_code'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_entity_type'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_entity_id'), table_name='workflow_events')
    op.drop_index(op.f('ix_workflow_events_discipline'), table_name='workflow_events')
    op.drop_index('ix_workflow_events_correlation', table_name='workflow_events')
    op.drop_index('ix_workflow_events_breakdown', table_name='workflow_events')
    op.add_column('staged_rows', sa.Column('created_asset_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('staged_rows', sa.Column('detected_type', postgresql.ENUM('ASSET', 'CONNECTION', 'LOCATION', 'UNKNOWN', name='detectedtype'), server_default=sa.text("'UNKNOWN'::detectedtype"), autoincrement=False, nullable=True))
    op.add_column('staged_rows', sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('staged_rows', sa.Column('mapped_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('staged_rows', sa.Column('status', postgresql.ENUM('PENDING', 'VALID', 'WARNING', 'ERROR', 'IMPORTED', name='ingeststatus'), server_default=sa.text("'PENDING'::ingeststatus"), autoincrement=False, nullable=True))
    op.add_column('staged_rows', sa.Column('validation_errors', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('staged_rows_created_asset_id_fkey'), 'staged_rows', 'assets', ['created_asset_id'], ['id'])
    op.create_index(op.f('ix_staged_rows_status'), 'staged_rows', ['status'], unique=False)
    op.create_index(op.f('ix_staged_rows_data_source_id'), 'staged_rows', ['data_source_id'], unique=False)
    op.alter_column('staged_rows', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('staged_rows', 'created_at')
    op.drop_column('staged_rows', 'asset_id')
    op.drop_column('staged_rows', 'import_status')
    op.drop_column('staged_rows', 'row_index')
    op.alter_column('rule_executions', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rule_executions', 'condition_matched',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('rule_definitions', 'failure_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('rule_definitions', 'success_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('rule_definitions', 'last_executed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('rule_definitions', 'execution_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('rule_definitions', 'version',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('rule_definitions', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rule_definitions', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('rule_definitions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('rule_definitions', 'is_enforced',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_property_changes_version', table_name='property_changes')
    op.alter_column('packages', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('packages', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('packages', 'metadata')
    op.drop_column('packages', 'package_type')
    op.create_foreign_key(op.f('metamodel_nodes_project_id_fkey'), 'metamodel_nodes', 'projects', ['project_id'], ['id'])
    op.create_index(op.f('ix_metamodel_nodes_type'), 'metamodel_nodes', ['type'], unique=False)
    op.create_index(op.f('ix_metamodel_nodes_project_id'), 'metamodel_nodes', ['project_id'], unique=False)
    op.create_index(op.f('ix_metamodel_nodes_discipline'), 'metamodel_nodes', ['discipline'], unique=False)
    op.alter_column('metamodel_nodes', 'semantic_type',
               existing_type=sa.Enum('CONTAINER', 'ASSET', 'LINK', name='semantictype'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('metamodel_nodes', 'data_source_id')
    op.drop_column('metamodel_nodes', 'confidence_score')
    op.drop_column('metamodel_nodes', 'description')
    op.drop_constraint('uix_metamodel_edge', 'metamodel_edges', type_='unique')
    op.create_index(op.f('ix_metamodel_edges_target'), 'metamodel_edges', ['target_node_id'], unique=False)
    op.create_index(op.f('ix_metamodel_edges_source'), 'metamodel_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_metamodel_edges_relation'), 'metamodel_edges', ['relation_type'], unique=False)
    op.alter_column('metamodel_edges', 'discipline',
               existing_type=sa.Enum('PROCESS', 'ELECTRICAL', 'AUTOMATION', 'MECHANICAL', 'PROJECT', 'PROCUREMENT', 'GENERAL', name='disciplinetype'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index('ix_lbs_project_id', table_name='lbs_nodes')
    op.create_index(op.f('ix_lbs_nodes_project_id'), 'lbs_nodes', ['project_id'], unique=False)
    op.add_column('data_sources', sa.Column('row_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('data_sources', sa.Column('headers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('data_sources', sa.Column('column_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('data_sources', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('data_sources', sa.Column('column_mapping', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('data_sources', sa.Column('stats', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('data_sources', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('data_sources', sa.Column('status', postgresql.ENUM('PENDING', 'MAPPING', 'VALIDATING', 'IMPORTING', 'COMPLETED', 'FAILED', name='importstatus'), server_default=sa.text("'PENDING'::importstatus"), autoincrement=False, nullable=True))
    op.add_column('data_sources', sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('data_sources', sa.Column('uploaded_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('data_sources', sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('data_sources_uploaded_by_fkey'), 'data_sources', 'users', ['uploaded_by'], ['id'])
    op.create_foreign_key(op.f('data_sources_project_id_fkey'), 'data_sources', 'projects', ['project_id'], ['id'])
    op.create_index(op.f('ix_data_sources_status'), 'data_sources', ['status'], unique=False)
    op.create_index(op.f('ix_data_sources_project_id'), 'data_sources', ['project_id'], unique=False)
    op.alter_column('data_sources', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('data_sources', 'updated_at')
    op.drop_column('data_sources', 'metadata_json')
    op.drop_column('data_sources', 'detected_type')
    op.drop_column('data_sources', 'ingest_status')
    op.drop_column('data_sources', 'file_hash')
    op.drop_index('ix_connection_project_id', table_name='connections')
    op.create_index(op.f('ix_connections_project_id'), 'connections', ['project_id'], unique=False)
    op.drop_index(op.f('ix_cables_to_asset_id'), table_name='cables')
    op.drop_index(op.f('ix_cables_from_asset_id'), table_name='cables')
    op.alter_column('cables', 'updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cables', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('cables', 'notes')
    op.drop_column('cables', 'created_by')
    op.drop_column('cables', 'part_number')
    op.drop_column('cables', 'manufacturer')
    op.drop_column('cables', 'flame_rating')
    op.drop_column('cables', 'temperature_rating')
    op.drop_column('cables', 'power_loss_watts')
    op.drop_column('cables', 'current_rating_amps')
    op.drop_column('cables', 'voltage_rating')
    op.drop_column('cables', 'conduit_size')
    op.drop_column('cables', 'installation_method')
    op.drop_column('cables', 'route_description')
    op.drop_column('cables', 'sheath_material')
    op.drop_column('cables', 'armor_type')
    op.drop_column('cables', 'insulation_type')
    op.drop_column('cables', 'conductor_material')
    op.drop_column('cables', 'construction')
    op.drop_column('cables', 'to_terminal')
    op.drop_column('cables', 'from_terminal')
    op.drop_index(op.f('ix_cable_types_part_number'), table_name='cable_types')
    op.alter_column('cable_types', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('cable_types', 'updated_at')
    op.drop_column('cable_types', 'lead_time_days')
    op.drop_column('cable_types', 'currency')
    op.drop_column('cable_types', 'unit_price_per_m')
    op.drop_column('cable_types', 'oil_resistant')
    op.drop_column('cable_types', 'sunlight_resistant')
    op.drop_column('cable_types', 'outdoor_rated')
    op.drop_column('cable_types', 'flame_rating')
    op.drop_column('cable_types', 'temp_range_celsius')
    op.drop_column('cable_types', 'min_bend_radius_mm')
    op.drop_column('cable_types', 'weight_kg_per_m')
    op.drop_column('cable_types', 'outer_diameter_mm')
    op.drop_column('cable_types', 'standards')
    op.drop_column('cable_types', 'temperature_rating')
    op.drop_column('cable_types', 'sheath_material')
    op.drop_column('cable_types', 'armor_type')
    op.drop_column('cable_types', 'construction')
    op.drop_index(op.f('ix_cable_sizing_rules_voltage_level'), table_name='cable_sizing_rules')
    op.drop_index(op.f('ix_cable_sizing_rules_application'), table_name='cable_sizing_rules')
    op.alter_column('cable_sizing_rules', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('cable_sizing_rules', 'notes')
    op.drop_column('cable_sizing_rules', 'table_number')
    op.drop_column('cable_sizing_rules', 'code_reference')
    op.drop_column('cable_sizing_rules', 'reactance_ohm_per_km')
    op.drop_column('cable_sizing_rules', 'max_voltage_drop_percent')
    op.drop_column('cable_sizing_rules', 'temperature_rating')
    op.drop_column('cable_sizing_rules', 'insulation_type')
    op.drop_column('cable_sizing_rules', 'conductor_material')
    op.drop_column('cable_sizing_rules', 'application')
    op.drop_index('ix_batch_operations_project_started', table_name='batch_operations')
    op.alter_column('batch_operations', 'is_rolled_back',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('audit_logs', sa.Column('changes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('entity_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('entity_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('audit_logs', sa.Column('project_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('audit_logs_project_id_fkey'), 'audit_logs', 'projects', ['project_id'], ['id'])
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'target_id')
    op.drop_column('audit_logs', 'target_type')
    op.drop_index('ix_asset_type_project', table_name='assets')
    op.drop_index('ix_asset_project_id', table_name='assets')
    op.create_index(op.f('ix_assets_type_project'), 'assets', ['type', 'project_id'], unique=False)
    op.create_index(op.f('ix_assets_project_id'), 'assets', ['project_id'], unique=False)
    op.drop_index('ix_asset_versions_batch', table_name='asset_versions')
    op.drop_index('ix_asset_changes_event', table_name='asset_changes')
    op.drop_index('ix_asset_changes_asset', table_name='asset_changes')
    op.alter_column('action_logs', 'timestamp',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
