"""add_data_status_to_assets

Revision ID: a678a9de6eb4
Revises: 72e11ad0ddbd
Create Date: 2025-11-21 21:49:59.767828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a678a9de6eb4'
down_revision: Union[str, None] = '72e11ad0ddbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use existing Enum 'assetdatastatus'
    op.add_column('assets', sa.Column('data_status', sa.Enum('FRESH_IMPORT', 'IN_REVIEW', 'VALIDATED', 'ERROR', name='assetdatastatus'), nullable=True))
    op.create_index(op.f('ix_assets_data_status'), 'assets', ['data_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_data_status'), table_name='assets')
    op.drop_column('assets', 'data_status')
    # ### end Alembic commands ###
