# =============================================================================
# HOMELAB INVENTORY - Updated 2025-12-02
# =============================================================================
# Auto-discovered by ATLAS via SSH exploration of NPM containers
# This file documents the homelab infrastructure for AI context persistence
# =============================================================================

---
metadata:
  discovered_date: "2025-12-01"
  updated_date: "2025-12-02"
  discovered_by: "ATLAS AI"
  source: "SSH exploration of pihole01/pihole02.home.s-gagnon.com (NPM containers)"
  owner: "seb"

# =============================================================================
# NETWORK TOPOLOGY
# =============================================================================
networks:
  main_lan:
    subnet: "192.168.1.0/24"
    description: "Main home network"
    gateway: "192.168.1.1"

  containers:
    subnet: "192.168.5.0/24"
    description: "LXC/Container network (Proxmox)"

  services:
    subnet: "192.168.10.0/24"
    description: "Services VLAN"

# =============================================================================
# PROXMOX HOSTS
# =============================================================================
proxmox_hosts:
  pve1:
    hostname: "pve1"
    ip: "192.168.1.20"
    port: 8006
    type: "Proxmox VE"
    urls:
      - "pve1.home.s-gagnon.com"
      - "pve1.s-gagnon.com"
    lxc_containers:
      - id: 100
        name: "homarr"
        docker: false
      - id: 101
        name: "unknown"
        docker: false
      - id: 102
        name: "unknown"
        docker: false
      - id: 210
        name: "pihole"
        ip: "192.168.5.10"
        service: "Pi-hole DNS v6"
        docker: false
      - id: 220
        name: "npm"
        ip: "192.168.5.20"
        service: "Nginx Proxy Manager"
        docker: false
      - id: 230
        name: "cloudflared"
        service: "Cloudflare Tunnel"
        docker: false
      - id: 405
        name: "unknown"
        docker: false
      - id: 461
        name: "unknown"
        docker: false
      - id: 462
        name: "unknown"
        docker: false
      - id: 470
        name: "wud"
        ip: "192.168.10.70"
        service: "What's Up Docker"
        docker: true
        containers:
          - wud
    virtual_machines:
      - id: 500
        name: "docker-00"
        ip: "192.168.10.50"
        service: "Docker Host"
        docker: true
        docker_tcp: 2375
        ssh_access: true
        containers:
          - portainer
          - grafana
          - prometheus
          - homepage
          - uptime-kuma
          - vscode-server
          - hbbs (RustDesk ID server)
          - hbbr (RustDesk relay)

  pve2:
    hostname: "pve2"
    ip: null  # To discover
    port: 8006
    type: "Proxmox VE"
    urls:
      - "pve2.home.s-gagnon.com"
    containers:
      - npm2 (Nginx Proxy Manager backup)

# =============================================================================
# CORE INFRASTRUCTURE
# =============================================================================
infrastructure:
  # Nginx Proxy Manager (Primary)
  npm1:
    hostname: "Nginx"
    ip: "192.168.5.20"
    type: "LXC Container"
    host: "pve1"
    service: "Nginx Proxy Manager"
    ports:
      - 80   # HTTP
      - 443  # HTTPS
      - 81   # Admin UI
      - 3000 # Node backend
    ssh_user: "root"
    ssh_access: true
    urls:
      - "npm.home.s-gagnon.com"
      - "pihole01.home.s-gagnon.com"  # Proxies to actual pihole
      - "pihole02.home.s-gagnon.com"  # Proxies to actual pihole

  # Nginx Proxy Manager (Secondary/HA)
  npm2:
    hostname: "Nginx"
    ip: "192.168.5.20"  # Same VIP as npm1 (keepalived/HA)
    type: "LXC Container"
    host: "pve2"
    service: "Nginx Proxy Manager (HA)"
    ssh_user: "root"
    ssh_access: true

  # Pi-hole (Actual DNS)
  pihole:
    hostname: "pihole"
    ip: "192.168.5.10"
    lxc_id: 210
    type: "LXC Container"
    host: "pve1"
    service: "Pi-hole DNS v6"
    ports:
      - 53   # DNS
      - 80   # Web UI
    urls:
      - "pihole-local.s-gagnon.com"
      - "pihole.local.s-gagnon.com"
    config:
      etc_dnsmasq_d: true  # Required for custom DNS entries
      custom_dns: "/etc/dnsmasq.d/05-custom-*.conf"
    notes: "Pi-hole v6 - Custom DNS via dnsmasq.d"

  # WUD (What's Up Docker)
  wud:
    hostname: "wud"
    ip: "192.168.10.70"
    lxc_id: 470
    type: "LXC Container (privileged)"
    host: "pve1"
    service: "What's Up Docker v8.1.1"
    ports:
      - 3000  # Web UI
    urls:
      - "wud.home.s-gagnon.com"
    docker: true
    watchers:
      - name: "local"
        type: "socket"
        target: "/var/run/docker.sock"
      - name: "docker00"
        type: "tcp"
        target: "192.168.10.50:2375"
    notes: "Auto-update manager for all Docker hosts"

  # Docker-00 (VM 500)
  docker00:
    hostname: "docker-00"
    ip: "192.168.10.50"
    vm_id: 500
    type: "Virtual Machine"
    host: "pve1"
    service: "Docker Host"
    docker_tcp: 2375
    ssh_access: true
    containers:
      - portainer
      - grafana
      - prometheus
      - homepage
      - uptime-kuma
      - vscode-server
      - hbbs
      - hbbr
    urls:
      - "portainer.home.s-gagnon.com"
    notes: "Main Docker host with TCP API exposed for WUD"

# =============================================================================
# STORAGE
# =============================================================================
storage:
  truenas:
    hostname: null
    ip: "192.168.1.59"  # Discovered from NPM database
    port: 443
    type: "TrueNAS"
    urls:
      - "truenas.home.s-gagnon.com"
      - "truenas.s-gagnon.com"
      - "truenas-local.s-gagnon.com"

# =============================================================================
# SERVICES DISCOVERED (via NPM proxy hosts)
# =============================================================================
services:
  # Security
  vaultwarden:
    ip: "192.168.1.123"
    type: "Password Manager"
    urls:
      - "vaultwarden.home.s-gagnon.com"
      - "vaultwarden.s-gagnon.com"
      - "vaultwarden-local.s-gagnon.com"

  # Home Automation
  homeassistant:
    ip: null  # To discover
    type: "Home Automation"
    urls:
      - "ha.home.s-gagnon.com"
      - "ha.s-gagnon.com"

  # Network
  udm:
    ip: null  # To discover
    type: "Unifi Dream Machine"
    urls:
      - "udm.home.s-gagnon.com"

  # Container Management
  portainer:
    ip: null  # To discover
    type: "Container Management"
    urls:
      - "portainer.home.s-gagnon.com"
      - "portainer.s-gagnon.com"
      - "portainer.axoiq.com"

  # Monitoring
  grafana:
    ip: null
    type: "Monitoring Dashboard"
    urls:
      - "grafana.home.s-gagnon.com"

  influxdb:
    ip: null
    type: "Time Series Database"
    urls:
      - "influxdb.home.s-gagnon.com"

  uptime_kuma:
    ip: null
    type: "Uptime Monitoring"
    urls:
      - "upkuma.home.s-gagnon.com"

  # Productivity
  n8n:
    ip: null
    type: "Workflow Automation"
    urls:
      - "n8n.home.s-gagnon.com"
      - "n8n.s-gagnon.com"

  outline:
    ip: null
    type: "Wiki/Documentation"
    urls:
      - "outline.home.s-gagnon.com"
      - "outline.s-gagnon.com"

  # Cloud/Files
  nextcloud:
    ip: null
    type: "Cloud Storage"
    urls:
      - "cloud.home.s-gagnon.com"
      - "cloud.s-gagnon.com"

  syncthing:
    ip: null
    type: "File Sync"
    urls:
      - "syncthing-nas.home.s-gagnon.com"

  # Development
  vscode:
    ip: null
    type: "VS Code Web"
    urls:
      - "vscode.home.s-gagnon.com"

  # AI
  ollama:
    ip: null
    type: "LLM Server"
    urls:
      - "ollama.axoiq.com"
      - "ollama.home.axoiq.com"

  webai:
    ip: null
    type: "AI Web Interface"
    urls:
      - "webai.home.s-gagnon.com"
      - "webai.s-gagnon.com"

  # RustDesk (Already deployed!)
  rustdesk:
    ip: null
    type: "Remote Desktop Server"
    urls:
      - "rustdesk.home.s-gagnon.com"
      - "rustdesk.s-gagnon.com"
      - "id.rustdesk.home.s-gagnon.com"
      - "relay.rustdesk.home.s-gagnon.com"
    notes: "Already deployed in homelab - can potentially reuse!"

  # Backup
  pbs:
    ip: null
    type: "Proxmox Backup Server"
    urls:
      - "pbs.home.s-gagnon.com"

  # Network Boot
  netbootxyz:
    ip: null
    type: "Network Boot"
    urls:
      - "netbootxyz.home.s-gagnon.com"

  # Dashboard
  homepage:
    ip: "192.168.10.10"
    port: 3000
    type: "Dashboard"
    urls:
      - "homepage.hl.s-gagnon.com"
      - "homepage-local.s-gagnon.com"

# =============================================================================
# CLIENT AI PROJECTS (via NPM)
# =============================================================================
ai_projects:
  bba_ai:
    urls: ["bba-ai.home.s-gagnon.com", "bba-ai.s-gagnon.com"]

  boralex_ai:
    urls: ["boralex-ai.home.s-gagnon.com", "boralex-ai.s-gagnon.com"]

  domtar_ai:
    urls: ["domtar-ai.home.s-gagnon.com", "domtar-ai.sgagnon.com"]

  laporte_ai:
    urls: ["laporte-ai.home.s-gagnon.com", "laporte-ai.s-gagnon.com"]

  ews_ai:
    urls: ["ews-ai.home.s-gagnon.com", "ews-ai.s-gagnon.com"]
    portainer: "port-ews.home.s-gagnon.com"

# =============================================================================
# DOMAINS
# =============================================================================
domains:
  primary:
    - s-gagnon.com          # Personal/homelab
    - axoiq.com             # ATLAS/AXIOM project (laptop)

  subdomains:
    home.s-gagnon.com: "Homelab services (internal)"
    local.s-gagnon.com: "Local network only"
    hl.s-gagnon.com: "Homelab (short)"
    home.axoiq.com: "AXIOM homelab"

# =============================================================================
# SSH ACCESS CONFIGURED
# =============================================================================
ssh_access:
  npm1:
    host: "pihole01.home.s-gagnon.com"
    user: "root"
    key: "~/.ssh/id_ed25519"
    status: "working"

  npm2:
    host: "pihole02.home.s-gagnon.com"
    user: "root"
    key: "~/.ssh/id_ed25519"
    status: "working"

# =============================================================================
# NOTES
# =============================================================================
notes:
  - "pihole01/pihole02.home.s-gagnon.com are actually NPM proxy entries, not Pi-hole"
  - "Real Pi-hole is LXC 210 at 192.168.5.10"
  - "Both NPM containers share IP 192.168.5.20 (likely keepalived VIP)"
  - "RustDesk (hbbs/hbbr) deployed on VM 500 Docker-00"
  - "WUD monitors all Docker hosts and auto-updates containers every 6 hours"
  - "VM 500 Docker TCP exposed on port 2375 (no TLS - internal network only)"
  - "Pi-hole v6 requires etc_dnsmasq_d=true in pihole.toml for custom DNS"

# =============================================================================
# TODO: Complete Discovery
# =============================================================================
to_discover:
  - "Get IPs for remaining services from NPM database"
  - "Map PVE2 container IDs and VMs"
  - "Document Tailscale/Headscale configuration"
  - "Identify LXC 100, 101, 102, 405, 461, 462 services"
