# AXIOM Infrastructure Registry
# Single source of truth for infrastructure configuration
# Version: 1.0
# Last updated: 2025-11-28

version: "1.0"

infrastructure:
  name: "AXIOM"
  domain: "axoiq.com"
  environment: "development"
  platform: "Docker + Docker Compose"
  orchestration: "Manual (Docker Compose)"

# ===========================
# PORT ALLOCATION REGISTRY
# ===========================
port_registry:
  # Port ranges by application
  ranges:
    forge:
      start: 3000
      end: 3999
      description: "FORGE shared infrastructure services"
      owner: "Platform Team"

    synapse:
      start: 4000
      end: 4999
      description: "SYNAPSE MBSE platform (MVP Dec 2025)"
      owner: "SYNAPSE Team"

    nexus:
      start: 5000
      end: 5999
      description: "NEXUS knowledge graph + notes/wiki"
      owner: "NEXUS Team"

    prism:
      start: 6000
      end: 6999
      description: "PRISM enterprise dashboard"
      owner: "PRISM Team"

    atlas:
      start: 7000
      end: 7999
      description: "ATLAS AI collaboration environment"
      owner: "ATLAS Team"

  # Currently allocated ports
  allocated:
    # FORGE Infrastructure
    5433:
      service: "forge-postgres"
      app: "forge"
      type: "database"
      internal_port: 5432
      protocol: "tcp"
      description: "PostgreSQL 15 - Shared database for all apps"
      networks: ["forge-network"]

    6379:
      service: "forge-redis"
      app: "forge"
      type: "cache"
      internal_port: 6379
      protocol: "tcp"
      description: "Redis 7 - Shared cache and pub/sub"
      networks: ["forge-network"]

    3000:
      service: "forge-grafana"
      app: "forge"
      type: "web"
      internal_port: 3000
      protocol: "http"
      description: "Grafana - Observability dashboard"
      networks: ["forge-network"]

    3080:
      service: "forge-wiki"
      app: "forge"
      type: "web"
      internal_port: 3080
      protocol: "http"
      description: "Docsify - Documentation wiki"
      networks: ["forge-network"]

    3100:
      service: "forge-loki"
      app: "forge"
      type: "log-aggregator"
      internal_port: 3100
      protocol: "http"
      description: "Loki - Log aggregation"
      networks: ["forge-network"]

    5050:
      service: "forge-pgadmin"
      app: "forge"
      type: "web"
      internal_port: 80
      protocol: "http"
      description: "pgAdmin 4 - PostgreSQL management"
      networks: ["forge-network"]

    5555:
      service: "forge-prisma"
      app: "forge"
      type: "web"
      internal_port: 5555
      protocol: "http"
      description: "Prisma Studio - Database browser"
      networks: ["forge-network"]

    7700:
      service: "forge-meilisearch"
      app: "forge"
      type: "search"
      internal_port: 7700
      protocol: "http"
      description: "MeiliSearch - Full-text search engine"
      networks: ["forge-network"]

    # Traefik (Reverse Proxy + SSL)
    80:
      service: "forge-traefik"
      app: "traefik"
      type: "http"
      internal_port: 80
      protocol: "http"
      description: "Traefik HTTP entrypoint"
      networks: ["forge-network"]

    443:
      service: "forge-traefik"
      app: "traefik"
      type: "https"
      internal_port: 443
      protocol: "https"
      description: "Traefik HTTPS entrypoint"
      networks: ["forge-network"]

    8888:
      service: "forge-traefik"
      app: "traefik"
      type: "dashboard"
      internal_port: 8080
      protocol: "http"
      description: "Traefik dashboard (dev only)"
      networks: ["forge-network"]

    # SYNAPSE Application
    4000:
      service: "synapse-frontend"
      app: "synapse"
      type: "web"
      internal_port: 4000
      protocol: "http"
      description: "SYNAPSE React 19 frontend (Vite dev server)"
      networks: ["default", "forge-network"]

    8001:
      service: "synapse-backend"
      app: "synapse"
      type: "api"
      internal_port: 8000
      protocol: "http"
      description: "SYNAPSE FastAPI backend"
      networks: ["default", "forge-network"]

    # NEXUS Application
    5173:
      service: "nexus-frontend"
      app: "nexus"
      type: "web"
      internal_port: 5173
      protocol: "http"
      description: "NEXUS frontend (Vite dev server)"
      networks: ["forge-network"]

    8000:
      service: "nexus-backend"
      app: "nexus"
      type: "api"
      internal_port: 8000
      protocol: "http"
      description: "NEXUS backend API"
      networks: ["forge-network"]

  # Available ports for future allocation
  available:
    synapse: "4002-4999"
    nexus: "5174-5999"
    prism: "6000-6999 (all available)"
    atlas: "7000-7999 (all available)"

# ===========================
# DOCKER NETWORKS
# ===========================
networks:
  forge-network:
    driver: "bridge"
    scope: "external"
    purpose: "Shared infrastructure network for all AXIOM applications"
    subnet: "auto"
    services:
      - "forge-postgres"
      - "forge-redis"
      - "forge-loki"
      - "forge-promtail"
      - "forge-grafana"
      - "forge-meilisearch"
      - "forge-traefik"
      - "forge-pgadmin"
      - "forge-prisma"
      - "forge-wiki"
      - "synapse-backend"
      - "synapse-frontend"
      - "nexus-backend"
      - "nexus-frontend"

  synapse-internal:
    driver: "bridge"
    scope: "internal"
    purpose: "SYNAPSE production internal network (isolated)"
    services:
      - "synapse-backend"
      - "synapse-frontend"
      - "synapse-nginx"
      - "synapse-ollama"
      - "synapse-redis"

  default:
    driver: "bridge"
    scope: "local"
    purpose: "Default network for docker-compose stacks"

# ===========================
# SERVICE INVENTORY
# ===========================
services:
  forge:
    - name: "forge-postgres"
      image: "postgres:15-alpine"
      ports: [5433]
      networks: ["forge-network"]
      volumes: ["postgres-data"]
      health_check: "pg_isready -U postgres"
      dependencies: []
      compose_file: "forge/docker-compose.yml"

    - name: "forge-redis"
      image: "redis:7-alpine"
      ports: [6379]
      networks: ["forge-network"]
      volumes: ["redis-data"]
      health_check: "redis-cli ping"
      dependencies: []
      compose_file: "forge/docker-compose.yml"

    - name: "forge-loki"
      image: "grafana/loki:2.9.0"
      ports: [3100]
      networks: ["forge-network"]
      volumes: ["loki-data", "./config/loki.yml"]
      health_check: "wget --spider http://localhost:3100/ready"
      dependencies: []
      compose_file: "forge/docker-compose.yml"

    - name: "forge-promtail"
      image: "grafana/promtail:2.9.0"
      ports: []
      networks: ["forge-network"]
      volumes: ["/var/lib/docker/containers", "./config/promtail.yml"]
      dependencies: ["forge-loki"]
      compose_file: "forge/docker-compose.yml"

    - name: "forge-grafana"
      image: "grafana/grafana:10.0.0"
      ports: [3000]
      networks: ["forge-network"]
      volumes: ["grafana-data"]
      health_check: "wget --spider http://localhost:3000/api/health"
      dependencies: ["forge-loki"]
      compose_file: "forge/docker-compose.yml"

    - name: "forge-meilisearch"
      image: "getmeili/meilisearch:v1.5"
      ports: [7700]
      networks: ["forge-network"]
      volumes: ["meili-data"]
      health_check: "curl http://localhost:7700/health"
      dependencies: []
      compose_file: "forge/docker-compose.yml"

    - name: "forge-pgadmin"
      image: "dpage/pgadmin4:latest"
      ports: [5050]
      networks: ["forge-network"]
      dependencies: ["forge-postgres"]
      compose_file: "forge/docker-compose.yml"

    - name: "forge-prisma"
      image: "prisma/studio:latest"
      ports: [5555]
      networks: ["forge-network"]
      dependencies: ["forge-postgres"]
      compose_file: "forge/docker-compose.yml"

    - name: "forge-wiki"
      image: "nginx:alpine"
      ports: [3080]
      networks: ["forge-network"]
      volumes: ["./docs"]
      dependencies: []
      compose_file: "forge/docker-compose.yml"

    - name: "forge-traefik"
      image: "traefik:v3.6.2"
      ports: [80, 443, 8888]
      networks: ["forge-network"]
      volumes: ["/var/run/docker.sock", "traefik-certs", "./config/traefik"]
      health_check: "traefik healthcheck --ping"
      dependencies: []
      compose_file: "forge/docker-compose.traefik.yml"

  synapse:
    dev:
      - name: "synapse-backend"
        image: "synapse-backend:dev"
        ports: [8001]
        networks: ["default", "forge-network"]
        volumes: ["./backend"]
        dependencies: ["forge-postgres", "forge-redis", "forge-loki", "forge-meilisearch"]
        compose_file: "apps/synapse/docker-compose.dev.yml"

      - name: "synapse-frontend"
        image: "synapse-frontend:dev"
        ports: [4000]
        networks: ["default", "forge-network"]
        volumes: ["./frontend/src"]
        dependencies: ["synapse-backend"]
        compose_file: "apps/synapse/docker-compose.dev.yml"

    prod:
      - name: "synapse-nginx"
        image: "nginx:alpine"
        ports: [80, 443]
        networks: ["synapse-internal", "forge-network"]
        volumes: ["./nginx.conf", "ssl-certs"]
        dependencies: ["synapse-backend", "synapse-frontend"]
        compose_file: "apps/synapse/docker-compose.yml"

  nexus:
    dev:
      - name: "nexus-backend"
        image: "nexus-backend:dev"
        ports: [8000]
        networks: ["forge-network"]
        dependencies: ["forge-postgres", "forge-redis"]
        compose_file: "apps/nexus/standalone/docker-compose.dev.yml"

      - name: "nexus-frontend"
        image: "nexus-frontend:dev"
        ports: [5173]
        networks: ["forge-network"]
        dependencies: ["nexus-backend"]
        compose_file: "apps/nexus/standalone/docker-compose.dev.yml"

# ===========================
# STARTUP ORDER (Dependency Chain)
# ===========================
startup_order:
  tier_1:
    description: "Core infrastructure (no dependencies)"
    services:
      - "forge-postgres"
      - "forge-redis"
    wait_for_healthy: true
    timeout: 30

  tier_2:
    description: "Secondary infrastructure (depends on tier 1)"
    services:
      - "forge-loki"
      - "forge-meilisearch"
    wait_for_healthy: true
    timeout: 20

  tier_3:
    description: "Monitoring and log collection"
    services:
      - "forge-promtail"
      - "forge-grafana"
    wait_for_healthy: true
    timeout: 15

  tier_4:
    description: "Reverse proxy and routing"
    services:
      - "forge-traefik"
    wait_for_healthy: true
    timeout: 10

  tier_5:
    description: "Application backends"
    services:
      - "synapse-backend"
      - "nexus-backend"
    wait_for_healthy: true
    timeout: 30

  tier_6:
    description: "Application frontends"
    services:
      - "synapse-frontend"
      - "nexus-frontend"
    wait_for_healthy: false
    timeout: 20

# ===========================
# VALIDATION RULES
# ===========================
validation_rules:
  ports:
    - rule: "no_duplicates"
      severity: "error"
      message: "Port {port} is already allocated to {existing_service}, cannot assign to {new_service}"

    - rule: "within_range"
      severity: "error"
      message: "Port {port} for app '{app}' must be in range {range_start}-{range_end}"

    - rule: "no_system_ports"
      severity: "error"
      message: "Port {port} is a system port (<1024). Use 80/443 only for Traefik or nginx."
      exception_services: ["forge-traefik", "synapse-nginx"]

    - rule: "expose_required"
      severity: "warning"
      message: "Service {service} has port {port} but no docker-compose port mapping. Add ports: ['{port}:{internal}']"

  networks:
    - rule: "forge_network_required"
      severity: "error"
      message: "Service {service} must be on 'forge-network' to access shared infrastructure (PostgreSQL, Redis, Loki, MeiliSearch)"
      applies_to:
        apps: ["synapse", "nexus", "prism", "atlas"]
      exemptions: ["nginx", "standalone"]

    - rule: "internal_isolation"
      severity: "warning"
      message: "Production services should use internal networks for security"
      applies_to:
        environments: ["production", "staging"]

  dependencies:
    - rule: "dependency_exists"
      severity: "error"
      message: "Service {service} depends on {dependency} which is not defined or not running"

    - rule: "no_circular_deps"
      severity: "error"
      message: "Circular dependency detected: {chain}"

    - rule: "startup_order"
      severity: "warning"
      message: "Service {service} should start AFTER {dependency} according to startup_order"

  health_checks:
    - rule: "critical_services_must_have_healthcheck"
      severity: "error"
      message: "Critical service {service} must define a health check"
      applies_to:
        types: ["database", "cache", "api"]

# ===========================
# ENVIRONMENT VARIABLES
# ===========================
environment:
  required_vars:
    forge:
      - name: "DOMAIN"
        default: "axoiq.com"
        description: "Base domain for Traefik routing"

      - name: "ACME_EMAIL"
        default: "admin@axoiq.com"
        description: "Email for Let's Encrypt SSL certificates"

      - name: "MEILI_MASTER_KEY"
        default: "synapse_dev_key_change_in_prod"
        description: "MeiliSearch master key"
        security: "secret"

    synapse:
      - name: "DATABASE_URL"
        description: "PostgreSQL connection string"
        format: "postgresql://user:pass@forge-postgres:5432/synapse"

      - name: "POSTGRES_SERVER"
        default: "forge-postgres"
        description: "PostgreSQL hostname (Docker DNS)"

      - name: "MEILISEARCH_URL"
        default: "http://forge-meilisearch:7700"
        description: "MeiliSearch URL (internal Docker network)"

      - name: "SECRET_KEY"
        description: "FastAPI secret key for JWT"
        security: "secret"
        generate: "openssl rand -hex 32"

    nexus:
      - name: "DATABASE_URL"
        description: "Main database connection"

      - name: "AUTH_DATABASE_URL"
        description: "Authentication database connection"

      - name: "WORKSPACE_SECRET_KEY"
        description: "Workspace encryption key"
        security: "secret"

  defaults:
    DOMAIN: "axoiq.com"
    ACME_EMAIL: "admin@axoiq.com"
    ENVIRONMENT: "development"
    LOG_LEVEL: "INFO"
    TZ: "America/New_York"

# ===========================
# SSL/TLS CONFIGURATION
# ===========================
ssl:
  provider: "mkcert"
  description: "Local development uses mkcert for trusted SSL certificates"

  certificate_path: "forge/config/traefik"

  certificates:
    - domain: "*.axoiq.com"
      cert_file: "axoiq.com.crt"
      key_file: "axoiq.com.key"
      wildcard: true
      valid_for:
        - "synapse.axoiq.com"
        - "api.axoiq.com"
        - "nexus.axoiq.com"
        - "traefik.axoiq.com"
        - "grafana.axoiq.com"

  traefik_config:
    file_provider_path: "/etc/traefik/dynamic"
    tls_mode: "file"  # "file" for mkcert, "acme" for Let's Encrypt
    acme_staging: true  # Use staging server for dev

  hosts_file:
    path: "C:\\Windows\\System32\\drivers\\etc\\hosts"
    entries:
      - "127.0.0.1 synapse.axoiq.com"
      - "127.0.0.1 api.axoiq.com"
      - "127.0.0.1 traefik.axoiq.com"
      - "127.0.0.1 nexus.axoiq.com"
      - "127.0.0.1 grafana.axoiq.com"

# ===========================
# DOCKER COMPOSE FILES
# ===========================
compose_files:
  forge:
    - path: "forge/docker-compose.yml"
      description: "Main FORGE infrastructure (PostgreSQL, Redis, Loki, Grafana, etc.)"
      services: 9

    - path: "forge/docker-compose.traefik.yml"
      description: "Traefik reverse proxy (overlay file)"
      services: 1
      usage: "docker-compose -f docker-compose.yml -f docker-compose.traefik.yml up -d"

  synapse:
    - path: "apps/synapse/docker-compose.dev.yml"
      description: "SYNAPSE development environment"
      services: 2
      networks: ["default", "forge-network"]

    - path: "apps/synapse/docker-compose.traefik-labels.yml"
      description: "Traefik labels for SYNAPSE (overlay file)"
      services: 2
      usage: "docker-compose -f docker-compose.dev.yml -f docker-compose.traefik-labels.yml up -d"

    - path: "apps/synapse/docker-compose.yml"
      description: "SYNAPSE production environment"
      services: 5
      networks: ["synapse-internal", "forge-network"]

  nexus:
    - path: "apps/nexus/standalone/docker-compose.dev.yml"
      description: "NEXUS development environment"
      services: 2

    - path: "apps/nexus/workspace/docker-compose.yml"
      description: "NEXUS workspace environment"
      services: 3

# ===========================
# MAINTENANCE
# ===========================
maintenance:
  backup:
    volumes_to_backup:
      - "postgres-data"
      - "redis-data"
      - "grafana-data"
      - "loki-data"
      - "meili-data"
    frequency: "daily"
    retention: "30 days"

  logs:
    retention: "7 days"
    aggregation: "Loki + Grafana"

  updates:
    check_frequency: "weekly"
    security_updates: "immediate"
    major_versions: "manual approval"

# ===========================
# METADATA
# ===========================
metadata:
  created: "2025-11-28 18:44"
  updated: "2025-11-28 18:44"
  version: "1.0"
  maintainer: "AXIOM Platform Team"
  documentation: ".dev/infra/infrastructure.md"
  changelog: ".dev/infra/CHANGELOG.md"
